package com.igh.eurekaapp.view;

import com.igh.eurekaapp.controller.CuentaController;
import com.igh.eurekaapp.util.Mensaje;
import java.awt.BorderLayout;
import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Gustavo Coronel
 */
public class ReporteMovimientosView extends javax.swing.JInternalFrame {

	/**
	 * Creates new form ConsultaCuentaView
	 */
	public ReporteMovimientosView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtCuenta = new javax.swing.JTextField();
      btnConsultar = new javax.swing.JButton();
      panelReporte = new javax.swing.JPanel();

      setClosable(true);
      setMaximizable(true);
      setResizable(true);
      setTitle("REPORTE DE MOVIMIENTOS");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CRITERIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 255))); // NOI18N

      jLabel1.setText("Cuenta:");

      btnConsultar.setText("Consultar");
      btnConsultar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConsultarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      panelReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

      javax.swing.GroupLayout panelReporteLayout = new javax.swing.GroupLayout(panelReporte);
      panelReporte.setLayout(panelReporteLayout);
      panelReporteLayout.setHorizontalGroup(
         panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 968, Short.MAX_VALUE)
      );
      panelReporteLayout.setVerticalGroup(
         panelReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 524, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

  private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
	  try {
		  // Datos del usuario
		  String cuenta = txtCuenta.getText();
		  // Obtener los datos
		  CuentaController control = new CuentaController();
		  List<Map<String, ?>> lista = control.conMovimientos(cuenta);
		  // Preparar reporte
		  JRMapCollectionDataSource data = new JRMapCollectionDataSource(lista);
		  Map pars = new HashMap();
		  String reporte = "/reportes/ReporteMovimientos.jrxml";
		  InputStream is = getClass().getResourceAsStream(reporte);
		  if (is == null) {
			  throw new RuntimeException("No carga el reporte.");
		  }
		  JasperReport rep = JasperCompileManager.compileReport(is);
		  JasperPrint print = JasperFillManager.fillReport(rep, pars, data);
		  // Se crea el visor del reporte
		  JRViewer jRViewer = new JRViewer(print);
		  // Se elimina elementos del contenedor JPanel
		  panelReporte.removeAll();
		  // Para el tamaño del reporte se agrega un BorderLayout
		  panelReporte.setLayout(new BorderLayout());
		  panelReporte.add(jRViewer, BorderLayout.CENTER);
		  jRViewer.setVisible(true);
		  panelReporte.repaint();
		  panelReporte.revalidate();
	  } catch (Exception e) {
		  e.printStackTrace();
		  Mensaje.error(rootPane, e.getMessage());
	  }
  }//GEN-LAST:event_btnConsultarActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnConsultar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel panelReporte;
   private javax.swing.JTextField txtCuenta;
   // End of variables declaration//GEN-END:variables
}
