/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.igh.eurekaapp.view;

import com.igh.eurekaapp.controller.CuentaController;
import com.igh.eurekaapp.util.Mensaje;

/**
 * @author Eric Gustavo Coronel Castillo
 * @blog www.desarrollasoftware.com
 * @email gcoronelc@gmail.com
 * @youtube www.youtube.com/DesarrollaSoftware
 * @facebook www.facebook.com/groups/desarrollasoftware
 * @cursos gcoronelc.github.io
 */
public class DepositoView extends javax.swing.JInternalFrame {

	/**
	 * Creates new form RetiroView
	 */
	public DepositoView() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jToolBar1 = new javax.swing.JToolBar();
      btnGrabar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtCuenta = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtImporte = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txtSaldo = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtMoneda = new javax.swing.JTextField();

      setClosable(true);
      setMaximizable(true);
      setTitle("PROCESO DEPOSITO");

      jToolBar1.setRollover(true);

      btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/igh/eurekaapp/img/grabar.png"))); // NOI18N
      btnGrabar.setToolTipText("Grabar");
      btnGrabar.setFocusable(false);
      btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnGrabar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnGrabarActionPerformed(evt);
         }
      });
      jToolBar1.add(btnGrabar);

      btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/igh/eurekaapp/img/cancelar.png"))); // NOI18N
      btnCancelar.setToolTipText("Cancelar");
      btnCancelar.setFocusable(false);
      btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      jToolBar1.add(btnCancelar);

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel1.setText("Cuenta");

      txtCuenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel2.setText("Importe");

      txtImporte.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel4.setText("Saldo");

      txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtSaldo.setDisabledTextColor(new java.awt.Color(0, 51, 204));
      txtSaldo.setEnabled(false);

      jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      jLabel5.setText("Moneda");

      txtMoneda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
      txtMoneda.setDisabledTextColor(new java.awt.Color(0, 51, 204));
      txtMoneda.setEnabled(false);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtImporte))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtSaldo))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtMoneda))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(174, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(282, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
		try {
			// Datos
			String cuenta = txtCuenta.getText();
			Double importe = Double.parseDouble(txtImporte.getText());
			// Proceso
			CuentaController controller = new CuentaController();
			controller.procDeposito(cuenta, importe);
			Mensaje.info(this, "Proceso ejecutado correctamente.");
		} catch (Exception e) {
			Mensaje.error(this, e.getMessage());
		}
   }//GEN-LAST:event_btnGrabarActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnGrabar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JTextField txtCuenta;
   private javax.swing.JTextField txtImporte;
   private javax.swing.JTextField txtMoneda;
   private javax.swing.JTextField txtSaldo;
   // End of variables declaration//GEN-END:variables

}
